### PR TITLE
padding top fix for contextual-help-drawer

### PR DESCRIPTION
**Pull request by umahaea**
Fix tests for "New app-header slightly overlaps the drawer.".
@mhomolak @udhadpa @StommePoes @wyseguyonline @JasonLantz for your review.

### CODE REVIEW

**Comment by udhadpa** [comment]
Looks good

**Comment by StommePoes** [comment]
so this problem was only on the mobile versions?

looks good

**Comment by umahaea** [comment]
wow, three approvals, so quick. Thank you! :)

**Comment by umahaea** [comment]
merging it.

**Comment by mhomolak** [comment]
@StommePoes All versions just due to the app-header having a larger height now.

**Pull request merged**
