### PR TITLE
feat(cnx-help): Add accordion and a11y tests

### PR DESCRIPTION
**Pull request by umahaea**
-> Add tests for below scenarios:
1. Test Accordion Content
2. Focus Forward Test in a Contextual Help Drawer
3. Focus Backward Test in a Contextual Help Drawer
4. Return Focus to where the user left off, outside conx-help-drawer
5. Return Focus to where the user left off, within conx-help-drawer
6. Trap Focus Within Drawer In Help Topics Details Test
-> Element identifiers(xpath) got changed, so update the new identifiers and fix broken tests
-> Comment out the styling tests here, as they will be verified with the next PR.
-> exclude two broken text-modal tests(payal will fix it and enable it later)

@StommePoes @udhadpa @wyseguyonline @JasonLantz @mhomolak for your review.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
Looks ok to me

**Comment by StommePoes** [comment]
looks ok.

**Comment by udhadpa** [comment]
looks good

**Comment by umahaea** [comment]
got max reviews, so going ahead with the merge.

**Pull request merged**
