### PR TITLE
feat(drawer): Add a11y tests

### PR DESCRIPTION
**Pull request by umahaea**
Add a11y tests for open, close, tabbing order-focus styles.
@StommePoes @wyseguyonline @udhadpa @JasonLantz @mhomolak

### CODE REVIEW

**Comment by StommePoes** [comment]
Looks good.

One thing I had a test for originally with karma was, while closing the drawer by clicking "close" inside of it should move the focus back to where the user was, in the demo there are additional buttons that close the drawer too. 

I have code in the Drawer that checks if my control closing the Drawer was inside the Drawer, or not. If it wasn't, focus doesn't go back to whatever opened it, but remains on the newly clicked thing (Hung said a student may open the Drawer, then click on a link or separate button somewhere on the page).

This isn't really an accessibility test (more usability) but that situation might also need a test.

**Comment by umahaea** [comment]
yes mallory, that's the check

**Comment by StommePoes** [comment]
ok looks good

**Comment by umahaea** [comment]
Incorporated mallory's comments.

**Comment by udhadpa** [comment]
looks good to me

**Pull request merged**
