### PR TITLE
feat(meter): Add meter tests

### PR DESCRIPTION
**Pull request by umahaea**
@StommePoes @antelopeb 
Include test for the &lt;progress&gt; element.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
Looks ok to me.

**Comment by antelopeb** [comment]
@StommePoes - do we need to include the <progress> element? I'm thinking we probably don't want that piece here, what do you think?

**Comment by StommePoes** [comment]
@antelopb since we have code for an actual progressbar, which the div version doesn't use, I thought it was a good idea to have a test using a real progressbar-- so that we *know* or already have tests showing that when we develop a React progressbar (so would be in Compounds SDK rather than Elements) that it will match the design spec.

I don't believe we need to add a <progress> to the Elements page since <meter> is basically our static Element and Progress will be our JavaScripted, dynamic Component. 

So I think  a <progress> belongs in the tests only because this is a weirdish situation where two elements share styles almost exactly, but leave our div-meter in Elements and keep the future progressbar only in Compounds. We may be building this one soon anyway.

**Comment by umahaea** [comment]
@StommePoes - r we good with this PR, do you have any further comments?

**Comment by StommePoes** [comment]
I'm good with this. This is the one I couldn't rebase, and it will probably merge kicking and screaming :P

**Comment by umahaea** [comment]
No problem, I will rebase it once with master and then merge it.

**Pull request merged**
