### PR TITLE
feat(alerts): fix test for capitalize

### PR DESCRIPTION
**Pull request by udhadpa**
Hello All,
Fixed test for capitalize alert types,
- changed alerts.html to reflect the change
- changed the id's in page objects file

@mhomolak @umahaea @wyseguyonline

### CODE REVIEW

**Comment by umahaea** [comment]
looks good to me.

**Comment by mhomolak** [comment]
looks good

**Comment by udhadpa** [comment]
Hello All,

Mike added box-shadow to alerts last night. I have now included a box-shadow test in my PR.

**Comment by umahaea** [comment]
looks good.

**Comment by StommePoes** [comment]
isBoxShadow looks good

**Comment by udhadpa** [comment]
Got approvals, good to merge

**Pull request merged**
