### PR TITLE
feat(drawer): Add tests for drawer component

### PR DESCRIPTION
**Pull request by umahaea**
Add tests for drawer component.
Desktop and mobile tests.
In BaseClass, moved all the page object class instantiation to a single method includePageObjects().
Also grouped all the OrigamiV2 tests to "desktop-regression" and "mobile-regression".

### CODE REVIEW

**Comment by umahaea** [comment]
@StommePoes and @veerabvm

**Comment by StommePoes** [comment]
Only thing I want to comment on is, if testing in real browsers, our test pages should have a doctype.

Before the <html lang="en"> line we *should* have, on all HTML pages, this:
<!DOCTYPE HTML>

Just for those browsers that have a quirks mode, and IE is not the only browser who has one. :)

Good move switching to the single method includePageObjects(), and I see the test for Hung's changes.

**Comment by veerabvm** [comment]
Please remove the Sauce Credentials from SauceParam.properties. Everything else looks good to me.

**Comment by umahaea** [comment]
closing and reopening it, as there are some conflicts.

**Pull request closed without merging**
