### PR TITLE
feat(colors): Add Colors Test

### PR DESCRIPTION
**Pull request by veerabvm**
Add Colors Test for Desktop and Mobile

### CODE REVIEW

**Comment by umahaea** [comment]
@StommePoes or @aaronkaka - would request one of you guys to also review the color tests.

**Comment by StommePoes** [comment]
For the buttons, esp the fake-link button, doesn't the test need some text inside the buttons?
```<button id="disabledButtonLink" class="pe-btn--link pe-btn--disabled"></button>```

**Comment by StommePoes** [comment]
```+            log.info("'" + cssPropertyType + "' :for Disabled Text Area is not as per the spec");``` line 69
is this the right error message?

**Comment by umahaea** [comment]
looks good to me, except for Mallory's comments.

**Comment by StommePoes** [comment]
Changes look good to me.

**Pull request merged**
